server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path:

wechat:
  config:
    domain: http://3htaxa.natappfree.cc
    webUrl: http://172.16.0.18:8081/
    appId:
    appSecret:
    token: token